#!/usr/bin/env python3
"""Regenerate DRAFT-DAY.md — the one page to read before/while drafting RPB.

Everything here is DERIVED from data/keepers-rpb.json and data/notes.json, so it can
never drift from them: re-run after any keeper, draft-order or FFA-list change.

    python3 draft_day.py            # writes DRAFT-DAY.md
    python3 draft_day.py --check    # self-check, writes nothing
"""
import json, sys, collections
from pathlib import Path

D = Path(__file__).parent / "data"
TEAMS, ROUNDS, MY_SLOT = 10, 16, 2
STARTERS = {"QB": 1, "RB": 2, "WR": 3, "TE": 1, "DST": 1, "K": 1}


def load():
    return (json.loads((D / "keepers-rpb.json").read_text()),
            json.loads((D / "notes.json").read_text()),
            json.loads((D / "plan-rpb.json").read_text()))


def slot_of(ov):
    """Snake seat for an overall pick. Even rounds run right to left."""
    rd, i = divmod(ov - 1, TEAMS)
    return i + 1 if rd % 2 == 0 else TEAMS - i


def ladder(kept_overalls):
    """Every overall pick that is actually made, keepers removed."""
    return [ov for ov in range(1, TEAMS * ROUNDS + 1) if ov not in kept_overalls]


def label(ov):
    rd, i = divmod(ov - 1, TEAMS)
    return f"{rd + 1}.{(i + 1):02d}"


def build():
    k, n, plan = load()
    order = {e["slot"]: e for e in k["draftOrder"]}
    slot_of_team = {e["team"]: e["slot"] for e in k["draftOrder"]}
    kept = collections.defaultdict(list)
    for x in k["keepers"]:
        kept[x["team"]].append(x)

    # A keeper consumes its owner's pick in that round, so it never comes up live.
    kept_ov = set()
    for x in k["keepers"]:
        rd, s = int(str(x["round"]).strip("R")), slot_of_team[x["player"] and x["team"]]
        base = (rd - 1) * TEAMS
        kept_ov.add(next(base + i for i in range(1, TEAMS + 1) if slot_of(base + i) == s))

    live = ladder(kept_ov)
    mine = [ov for ov in live if slot_of(ov) == MY_SLOT]

    # Needs per team, keepers already deducted.
    needs = {}
    for s in range(1, TEAMS + 1):
        t = order[s]["team"]
        have = collections.Counter(x["pos"] for x in kept[t])
        needs[s] = {p: STARTERS[p] - have.get(p, 0) for p in STARTERS
                    if STARTERS[p] - have.get(p, 0) > 0}

    # FFA lists, with anyone already kept by a rival struck off — they never come up.
    shared = n["shared"]
    kept_names = {x["player"].lower().split(" jr")[0] for x in k["keepers"]}
    def is_kept(name):
        return any(kn in name.lower() or name.lower() in kn for kn in kept_names)
    musts = [v for v in shared.values() if v.get("call") == "must"]
    shys = [v for v in shared.values() if v.get("call") == "shy"]

    out = []
    w = out.append
    w("# RPB draft day — one page\n")
    w(f"Generated by `draft_day.py` from `data/keepers-rpb.json` ({k['updated']}) "
      f"and `data/notes.json` ({n['updated']}). Re-run after any change to either.\n")
    w("You are **slot 2**, 10 teams, 16 rounds, half-PPR, D/ST scores double.\n")

    w("\n## Your picks\n")
    w("`" + "` · `".join(label(o) for o in mine) + "`\n")
    w(f"\n{len(mine)} live picks (round 10 is consumed by the Etienne keeper).\n")

    w("\n## The plan — Monte Carlo\n")
    w(f"{plan['source']}\n")
    w("\n| branch | when | do | why |")
    w("|---|---|---|---|")
    for b in plan["branches"]:
        w(f"| **{b['tag']}** | {b['when']} | **{b['do']}** | {b['why']} |")
    w(f"\n**Take zone (RB cutoff at 2.09):** {' · '.join(plan['takeZone'])}.")
    w(f"\n{plan['takeZoneNote']}\n")
    w(f"\n**{plan['bowers']} rule:** if he is on the board, take him — {plan['bowersGain']}. "
      f"⚠ {plan['bowersRule']}\n")
    w(f"\n**Round-2 edge:** {plan['edge']}\n")
    w("\n**Do not:**\n")
    for t in plan["traps"]:
        w(f"- {t}")
    w("\n**Standing conclusions:**\n")
    for s in plan["standing"]:
        w(f"- {s}")

    w("\n\n### Contingencies — the branches the sims called impossible\n")
    w("Both 0% branches fired in a single mock. Treat every 'never happens' number in "
      "`sims/README.md` as *rare, not impossible*.\n")
    w("\n| if | then | why |")
    w("|---|---|---|")
    for c in plan["contingencies"]:
        w(f"| {c['when']} | **{c['do']}** | {c['why']} |")

    w("\n## Block windows — the only places blocking is real\n")
    w("At your **turn picks** only two or three players come off between your picks, so taking "
      "the one player a specific rival wants actually denies him. At your **wrap picks** the whole "
      "room goes twice — you cannot deny eight teams, so just take the better player.\n")
    w("\n| your pick | gap | who picks before your next | skill needs |")
    w("|---|---|---|---|")
    skill = lambda s: " ".join(f"{v}{p}" for p, v in needs[s].items() if p not in ("DST", "K"))
    for a, b in zip(mine, mine[1:]):
        between = [slot_of(o) for o in live if a < o < b]
        uniq = list(dict.fromkeys(between))
        if len(uniq) <= 3:
            who = "; ".join(f"**{order[s]['manager']}** ({skill(s)})" for s in uniq)
            w(f"| **{label(a)}** | {len(between)} picks | {who} | — |")
        else:
            w(f"| {label(a)} | {len(between)} picks | whole room ({len(uniq)} teams) "
              f"| nothing to block — take value |")
    w(f"| {label(mine[-1])} | last pick | — | — |")

    w("\n## League needs at kickoff\n")
    w("| slot | team | mgr | keeps | needs |")
    w("|---|---|---|---|---|")
    for s in range(1, TEAMS + 1):
        e = order[s]
        ks = ", ".join(f"{x['player']} {x['pos']} R{x['round']}" for x in kept[e["team"]]) or "—"
        nd = " ".join(f"{v}{p}" for p, v in needs[s].items())
        me = " **(you)**" if s == MY_SLOT else ""
        w(f"| {s} | {e['team']}{me} | {e['manager']} | {ks} | {nd} |")

    qb_short = sum(1 for s in needs if "QB" in needs[s])
    te_short = sum(1 for s in needs if "TE" in needs[s])
    rb_slots = sum(needs[s].get("RB", 0) for s in needs if s != MY_SLOT)
    w(f"\n- Only **{qb_short} of {TEAMS} teams need a QB** — six keep one. Nobody can block you at QB; wait.")
    w(f"- **{te_short} of {TEAMS} teams need a TE.** Scarcest starting slot in the league.")
    w(f"- **{rb_slots} opponent RB slots open** against one kept RB. This is where the room collides.\n")

    w("\n## FFA must-draft — live targets\n")
    gone = [v for v in musts if is_kept(v["name"])]
    for pos in ["RB", "WR", "TE", "QB"]:
        rows = [v for v in musts if v["pos"] == pos and not is_kept(v["name"])]
        if rows:
            w(f"\n**{pos}** — " + " · ".join(sorted(v["name"] for v in rows)))
    if gone:
        w("\n\n**Kept by a rival, never reaches the draft:** "
          + " · ".join(f"{v['name']} ({v['pos']})" for v in sorted(gone, key=lambda x: x["name"])))
    w("\n\nYou start one QB and one TE. Once those two slots are filled, every remaining "
      "QB/TE must-draft is noise — ignore them.\n")

    fmt = n.get("rpbFormat")
    if fmt:
        w("\n## Half-PPR format splits — where Nick's advice moves in YOUR league\n")
        w("His notes are written for 12-team full-PPR with a FLEX. RPB is half-PPR, 2RB/3WR, no "
          "FLEX, D/ST doubled, no playoffs. These are the players whose verdict changes.\n")
        w("\n**Better in RPB than his rank implies:**\n")
        for nm, why in fmt["up"].items():
            w(f"- **{nm}** — {why}")
        w("\n**Worse in RPB — discount or avoid:**\n")
        for nm, why in fmt["down"].items():
            w(f"- **{nm}** — {why}")
        w("\n**Structural differences to keep in mind:**\n")
        for line in fmt["structural"]:
            w(f"- {line}")

    w("\n## FFA shy-away — do not draft\n")
    for v in sorted(shys, key=lambda x: x["name"]):
        why = (v.get("why") or v.get("note") or "").strip()
        w(f"- **{v['name']}** ({v['pos']}) — {why[:150]}")

    w("\n## Reading the FantasyPros sim\n")
    w("- **Cheat Sheets tab** is the view: set `RPB 2026` + `Pick Predictor: One round` + `Hide Drafted ✓`. "
      "Only place rank, predictor %, ADP and notes appear together. Position tabs across the top.")
    w("- **Pick Predictor %** = chance he's gone before your next pick. At a turn, take the high-% "
      "player and expect the low-% one to come back.")
    w("- **Set the predictor horizon to match the gap.** Your turn picks have a 2-player gap, so "
      "`One round` overstates risk there. Your wrap picks have a ~17-player gap — nearly two "
      "rounds — so switch the dropdown to `Two rounds` before every wrap pick or the number lies to you.")
    w("- **Suggestions tab right rail** lists every team picking before your turn with its needs badges.")
    w("- **Suggestions → Draft Strategy → team dropdown** shows what the engine would pick *for an opponent*.")
    w("- **Trust the rank column over 'Top Suggestion'** — they disagree often, and the suggestion "
      "has pushed FFA-avoid players (Christian Watson, Jameson Williams).")
    w("- **Pause is ▶/⏸ top right — verify the timer actually froze.** A pause that doesn't take "
      "costs a pick to autodraft.")
    w("- `get_page_text` returns nothing and `read_page` is unusable on that page. Screenshots only.\n")
    return "\n".join(out), dict(live=live, mine=mine, needs=needs, kept_ov=kept_ov, plan=plan)


def check(meta):
    """The pick ladder is the only arithmetic here nothing else exercises."""
    f = []
    ok = lambda c, m: None if c else f.append(m)
    ok(len(meta["live"]) == TEAMS * ROUNDS - len(meta["kept_ov"]),
       "live picks = full ladder minus keepers")
    ok(slot_of(1) == 1 and slot_of(TEAMS) == TEAMS, "round 1 runs left to right")
    ok(slot_of(TEAMS + 1) == TEAMS and slot_of(2 * TEAMS) == 1, "round 2 reverses")
    ok(all(slot_of(o) == MY_SLOT for o in meta["mine"]), "every pick of yours sits in your seat")
    ok(len(meta["mine"]) == ROUNDS - 1, f"16 rounds minus the R10 keeper = 15 picks, got {len(meta['mine'])}")
    ok(not any(o in meta["kept_ov"] for o in meta["live"]), "no keeper pick ever comes up live")

    # plan-rpb.json and index.html's PLAN constant say the same thing in two places so the app
    # can render offline. Nothing keeps them honest but this: edit one, edit the other.
    plan, app = meta["plan"], (Path(__file__).parent / "index.html").read_text()
    for name in plan["takeZone"] + [plan["bowers"], plan["cutoffAfter"], plan["pivotFrom"]]:
        ok(name in app, f"'{name}' is in plan-rpb.json but not in index.html's PLAN — they have drifted")
    ok("nextRd>=2" in app.replace(" ", ""),
       "the round-2 gate on the Bowers rule is gone from index.html — taking him at 1.02 costs -81.8")
    return f


if __name__ == "__main__":
    md, meta = build()
    fails = check(meta)
    if fails:
        print("FAIL:\n  " + "\n  ".join(fails)); sys.exit(1)
    if "--check" in sys.argv:
        print(f"OK — {len(meta['mine'])} picks, {len(meta['live'])} live of {TEAMS * ROUNDS}")
    else:
        Path(__file__).with_name("DRAFT-DAY.md").write_text(md)
        print(f"wrote DRAFT-DAY.md — {len(md.splitlines())} lines, {len(meta['mine'])} of your picks")
