#!/usr/bin/env python3
"""Generate TAKE-CARD.md — the live-draft decision card.

The point: during a draft there is no time to reason. Every pick becomes
"scan the list top-down, take the first name still on the board that fills an
unfilled need." All the thinking is done here, ahead of time.

Input : RPB-TARGETS-160.csv (already fade/shy-filtered, musts bumped)
Output: TAKE-CARD.md

    python3 sims/takecard.py            # write TAKE-CARD.md
    python3 sims/takecard.py --selftest
"""

import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGETS = os.path.join(ROOT, "RPB-TARGETS-160.csv")
OUT = os.path.join(ROOT, "TAKE-CARD.md")

TEAMS = 10
ROUNDS = 16
SLOT = 2
KEEPER_ROUND = 10
KEEPER = "Luther Burden III (WR, bye 10)"

# Starters: QB1 RB2 WR3 TE1 K1 DST1, no FLEX. Burden fills one WR.
STARTERS = {"QB": 1, "RB": 2, "WR": 3, "TE": 1, "DST": 1, "K": 1}
# ponytail: bench caps are soft guidance, not enforced anywhere but this table
BENCH_TARGET = {"RB": 2, "WR": 2}


def my_picks():
    """(round, 'r.pp', overall) for every pick, keeper round excluded."""
    out = []
    for rnd in range(1, ROUNDS + 1):
        if rnd == KEEPER_ROUND:
            continue
        slot = SLOT if rnd % 2 else TEAMS - SLOT + 1
        out.append((rnd, "%d.%02d" % (rnd, slot), (rnd - 1) * TEAMS + slot))
    return out


def load():
    with open(TARGETS) as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        # D/ST and K carry no VBD or ADP — FFA projects neither. Fall back to
        # the board's own rank so they still land in the right pick band.
        r["vbd"] = float(r["vbd"]) if r["vbd"] else 0.0
        r["adp"] = int(r["adp"]) if r["adp"] else int(r["rank"])
        r["must"] = r["ffa"].strip().upper() == "MUST"
    return rows


def line(i, r):
    star = " *" if r["must"] else ""
    return "%3d. %-3s %-24s %-4s %+7.1f  adp %3d%s" % (
        i, r["pos"], r["name"], r["team"], r["vbd"], r["adp"], star)


def band(rows, overall, nxt, width=8):
    """Players plausibly on the board at `overall` and worth taking there.

    ADP is noisy, so the window opens 8 picks early (guys who fall) and runs to
    the next pick (anyone who survives that long was never a decision here).
    """
    lo, hi = overall - 8, (nxt if nxt else overall + 20)
    hits = [r for r in rows if lo <= r["adp"] <= hi]
    hits.sort(key=lambda r: (-r["vbd"], r["adp"]))
    return hits[:width]


def render(rows):
    picks = my_picks()
    L = []
    A = L.append

    A("# RPB take card — slot 2\n")
    A("Generated by `sims/takecard.py` from `RPB-TARGETS-160.csv`. "
      "Regenerate after any board change.\n")
    A("Keeper: **%s**, consumes 10.09.\n" % KEEPER)

    A("## The algorithm — do this, do not think\n")
    A("1. Read the board. 2. Scan THE LIST top-down. 3. Take the first name "
      "still available that fills an unfilled need. 4. Click.\n")
    A("- Not on the list = not a target. The list is already cut for FFA "
      "shy-away / avoid / fade.\n")
    A("- `*` = FFA must-draft. Breaks ties only; it is not a shopping list.\n")
    A("- Need is unfilled until the starter slot is full. No FLEX — a 3rd RB "
      "is bench, and bench never outranks an open starter.\n")
    A("- D/ST at 13.02, K at 16.09. Never earlier. Never reach.\n")
    A("- One TE. Once Bowers (or his replacement) is in, every other TE is noise.\n")

    A("\n### Two rules that override everything above\n")
    A("**4.09 IS THE RB2 PICK.** Love (adp 31), Hall (34), Javonte (38) all land "
      "on overall 39. Take one. If all three are gone, Montgomery (55) or Swift "
      "(53) at 5.02 — then stop. Below Swift the board falls off a cliff "
      "(Judkins -8.5, then nothing).\n")
    A("**ORDER OF OPERATIONS: RB2 FIRST AT 4.09, WASHINGTON NEXT AT 5.02.** "
      "That is the whole early-round plan. Never flip it — the back is the "
      "scarce thing, Washington is the cheap thing.\n")
    A("**PARKER WASHINGTON — TAKE HIM ONE TO TWO ROUNDS EARLY.** Plan slot is "
      "6.09; take him at 5.02 instead (4.09 only if RB2 is already filled). "
      "Do not wait for ADP. Measured "
      "2026-08-08: 23-28% gone at 5.02 but 76% at 6.09 in the SAME draft — the "
      "window shuts between those two picks. He is +23.4 VBD at FFA ADP 73, the "
      "largest value-vs-cost gap on the board, and it exists only because no "
      "ranking prices the punt-return work RPB pays for. Reaching costs ~7 pts "
      "(the WRs at 4.09-5.02 are +13 to +16); missing him costs 23.\n")
    A("**CLEAR OR REORDER THE QUEUE BEFORE THE DRAFT.** Verified 2026-08-08: "
      "the Queue auto-fills from this sheet's must-draft stars, and autodraft "
      "pulls from it. A missed 1.02 took Amon-Ra St. Brown (rank 6) over Bijan "
      "(rank 2) — a 76-point error. The must-draft list is a tiebreaker, not a "
      "value ranking.\n")
    A("**ONE CLICK PER PICK, THEN WAIT 5-8s.** The draft UI lags several "
      "seconds behind a successful click. A stale board reads as 'it did not "
      "register'; clicking again spends the NEXT pick. Confirm by the pick "
      "number in the header, never by the player list.\n")
    A("**PRE-COMMIT TURN PICKS AS A PAIR** (2.09/3.02, 4.09/5.02, 6.09/7.02, "
      "8.09/9.02, 12.09/13.02, 14.09/15.02). Opponents on auto pick instantly, "
      "so a turn gap can be ~5 seconds — shorter than one board read.\n")
    A("**NO QB BEFORE ROUND 7.** Six teams keep a quarterback and only three "
      "opponents ever need one. Measured 2026-08-08: Burrow was on the board at "
      "9.02 and Herbert survived to 15.02 at 77%. Spending 4.09 on Allen cost "
      "41 points of RB2 to gain 16 of QB — a net -25. Round 7 is the floor, not "
      "the target; later is fine.\n")

    A("\n## Needs tracker\n")
    A("| pos | starters | filled by keeper | still needed | bench target |")
    A("|---|---|---|---|---|")
    for pos in ("QB", "RB", "WR", "TE", "DST", "K"):
        kept = 1 if pos == "WR" else 0
        A("| %s | %d | %d | **%d** | %d |" % (
            pos, STARTERS[pos], kept, STARTERS[pos] - kept,
            BENCH_TARGET.get(pos, 0)))

    A("\n## Your picks\n")
    A("`" + "` · `".join(p[1] for p in picks) + "`\n")
    A("15 live picks. Round 10 is the keeper.\n")

    A("\n## Per-pick band — who you are actually choosing among\n")
    A("Ordered by VBD. If none are left, drop to THE LIST and take the best "
      "name that fills a need.\n")
    for idx, (rnd, label, overall) in enumerate(picks):
        nxt = picks[idx + 1][2] if idx + 1 < len(picks) else None
        A("\n### %s  (overall %d)" % (label, overall))
        if label == "3.02":
            A("**WR PICK.** The take zone is empty by pick 19 in six straight "
              "mocks. A surviving back is a bonus, never the plan.")
        if label == "4.09":
            A("**RB2 HERE — NON-NEGOTIABLE.** Best available of Love / Hall / "
              "Javonte. Not a QB. Not a WR. "
              "EXCEPTION: if RB2 is already filled, this is the Parker "
              "Washington pick — take him here, not at 6.09.")
        if label == "5.02":
            A("**PARKER WASHINGTON HERE.** This is his pick. He was 23-28% gone "
              "at this pick and 76% one pick later — 6.09 is too late. Only "
              "skip him if RB2 is somehow still open, in which case take the "
              "back and he is gone.")
        if rnd == 13:
            A("**D/ST HERE.** Seattle first, Jacksonville only if churning weekly. "
              "Houston is the trap.")
        if rnd == 16:
            A("**KICKER HERE.** Do not spend thought.")
        hits = band(rows, overall, nxt)
        if not hits:
            A("_nothing in band — take best available off THE LIST_")
        else:
            A("```")
            for i, r in enumerate(hits, 1):
                A(line(i, r))
            A("```")

    A("\n## THE LIST — %d deep, board order\n" % len(rows))
    A("```")
    for i, r in enumerate(rows, 1):
        A(line(i, r))
    A("```")
    return "\n".join(L) + "\n"


def selftest():
    picks = my_picks()
    assert len(picks) == 15, picks
    assert picks[0] == (1, "1.02", 2), picks[0]
    assert picks[1] == (2, "2.09", 19), picks[1]
    assert picks[2] == (3, "3.02", 22), picks[2]
    assert ("10.09" not in [p[1] for p in picks]), "keeper round must be excluded"
    assert picks[-1] == (16, "16.09", 159), picks[-1]
    # overall numbers must match what the simulator showed us live
    assert [p[2] for p in picks][:9] == [2, 19, 22, 39, 42, 59, 62, 79, 82]
    rows = load()
    assert len(rows) == 160
    assert rows[0]["name"] == "Jahmyr Gibbs"
    b = band(rows, 22, 39)
    assert b, "3.02 band should not be empty"
    assert all(14 <= r["adp"] <= 39 for r in b), b
    assert b == sorted(b, key=lambda r: (-r["vbd"], r["adp"]))
    print("selftest OK")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        with open(OUT, "w") as fh:
            fh.write(render(load()))
        print("wrote %s" % OUT)
